#!/bin/sh

# Run this while chrooted into a fresh Arch install.

grep '^\[instant\]$' /etc/pacman.conf || echo '
[instant]
SigLevel = Optional TrustAll
Server = https://instantos.surge.sh' >> /etc/pacman.conf

pacman -Syu --needed base-devel yay
sudo sed -i 's/.*\(%wheel ALL=(ALL) ALL\).*/\1/' /etc/sudoers
printf "username: " && read -r user
useradd -m "$user"
passwd --status "$user" || passwd "$user"
gpasswd -a "$user" wheel
sudo -u "$user" yay -S --needed yadm
sudo -u "$user" yadm clone https://github.com/dennisleexyz/dotfiles
sudo -u "$user" yadm bootstrap
