#!/bin/sh

echo '
[instant]
Server = https://instantos.surge.sh' >> /etc/pacman.conf
pacman -Syu yay

# https://www.thinkwiki.org/wiki/Integrated_Fingerprint_Reader#Models_featuring_this_Technology
if lsusb | grep -Ey 'upek touch[[:alpha:]]{2,3}ip'; then
	pacman -S xf86-input-wacom && {
		# shellcheck disable=2016
		echo 'export XAUTHORITY="/run/user/1000/gdm/Xauthority"
export DISPLAY=:0
case "$4" in
	00000000)
		xrandr --output LVDS1 --rotate normal
		xsetwacom set 17 rotate none
		xsetwacom set 18 rotate none
		xsetwacom set 24 rotate none
		;;
	00000001)
		xrandr --output LVDS1 --rotate inverted
		xsetwacom set 17 rotate half
		xsetwacom set 18 rotate half
		xsetwacom set 24 rotate half
		;;
esac' > /etc/acpi/actions/tabletmode.sh &&
		echo 'event=video/tabletmode
action=/etc/acpi/actions/tabletmode.sh'
	}

	# https://wiki.archlinux.org/index.php/Fprint
	pacman -S gdm && systemctl enable -f gdm && {
	# pacman -S sddm && systemctl enable -f sddm && {
		echo 'polkit.addRule(function (action, subject) {
	if (action.id == "net.reactivated.fprint.device.enroll") {
		return subject.user == "root" ? polkit.Result.YES : polkit.result.NO
	}
})' > /usr/share/polkit-1/rules.d/50-net.reactivated.fprint.device.enroll.rules

		# https://wiki.archlinux.org/index.php/Display_manager#Run_~/.xinitrc_as_a_session
		yay -S xinit-xsession
	}

	# yay -S thinkpad-scripts && {
	#	udevadm trigger --action=change
	#	systemctl restart acpid
	# }

	# pacman -Sy \
	# 	instantwm \
	# 	instantassist \
		# instantutils \
		# ttf-nerd-fonts-symbols \
		# instantdepend \
		# cantarell-fonts \
		# instantwm \
		# --assume-installed instantshell \
		# --assume-installed instantdotfiles \
else
	pacman -S sx
fi

# https://wiki.archlinux.org/index.php/Polkit#Authentication_agents
pacman -S \
	man \
	neovim \
	lxqt-policykit \

# pacman -S connman && systemctl enable connman
# pacman -S netctl && systemctl enable netctl

echo '
GRUB_CMDLINE_LINUX_DEFAULT="quiet cryptdevice=UUID=72fee427-1174-4172-871e-c2ced1daefc2:luks-72fee427-1174-4172-871e-c2ced1daefc2 root=/dev/mapper/luks-72fee427-1174-4172-871e-c2ced1daefc2 resume=/dev/mapper/luks-72fee427-1174-4172-871e-c2ced1daefc2 udev.log_priority=3"
GRUB_ENABLE_CRYPTODISK=y
GRUB_TIMEOUT_STYLE=hidden' >> /etc/default/grub

echo '
UseSyslog
Color
TotalDownload
VerbosePkgLists

[multilib]
Include = /etc/pacman.d/mirrorlist

# [pcr]
# SigLevel = PackageRequired
# Server = https://redirector.parabola.nu/$repo/os/$arch

# [kernels]
# SigLevel = PackageRequired
# Server = https://redirector.parabola.nu/$repo/os/$arch

# [nonprism]
# SigLevel = PackageRequired
# Server = https://redirector.parabola.nu/$repo/os/$arch

# [libre]
# SigLevel = PackageRequired
# Server = https://redirector.parabola.nu/$repo/os/$arch

# [nonsystemd]
# SigLevel = PackageRequired
# Server = https://redirector.parabola.nu/$repo/os/$arch

[instant]
SigLevel = Optional TrustAll
Server = https://instantos.surge.sh' >> /etc/pacman.conf
