#!/bin/sh

: "
NAME
	dwallpaper - Dynamic Wallpaper
EXAMPLE
	0 * * * * . $HOME/.profile; dynawall $HOME/.local/share/wg/catalina
"

export DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS:-unix:path=${XDG_RUNTIME_DIR:-/run/user/$(id -ur)}/bus}
export DISPLAY=${DISPLAY:-:0}
export XAUTHORITY=${XAUTHORITY:-"$HOME/.Xauthority"}

f="$1/$(date +%H).jpg"

setbg "$f" || notify-send -u critical -i "$f" "$(basename "$0")" "$f: No such file or directory"
