#!/bin/sh

: "
NAME
	hugodate - Hugo Date Formatter
SEE ALSO
	https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases
	https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
"

date="$(date -Is)"

if grep 'date: ' "$1"; then
	sed -i "s/date: .*/date: $date/" "$1"
else
	sed -i "s/slug: /date: $date\nslug: /" "$1"
fi

file=$(readlink -f "$1")
dir=${file%/*}
name="$(echo "$file" | grep -oE '/[^/]*$' | sed 's,/,,')"

mv "$1" "$dir/$(date -I)-$name"
