#!/bin/sh

: "
NAME
	instantparabola - instantOS install wrapper for use with Parabola repos

DESCRIPTION
	Installs instantOS, making only the necessary changes to its installer for
	it to work from Parabola's repos and live CLI ISO.
"

# This worked for me to fix "package installation failed". As of writing,
# latest Parabola ISO comes with old keys that must be refreshed.
pacman-key --refresh-keys
pacman-key --populate parabola

# Next 2 lines are technically redundant on fresh boot of Parabola ISO, but
# included for safety.
cd /root || exit
[ -d instantARCH ] && rm -rf instantARCH

pacman -Sy --noconfirm git
git clone https://github.com/instantos/instantARCH.git
cd instantARCH || exit
git checkout f07cf46c5a1047054caae02d76077088b73cfb78
find ./* -type f -exec sed -i '
	s/ARCHlinux\.org/parabola.nu/g;
	s/linux/linux-libre/g;
	/^\[ -e instantARCH \] && rm -rf instantARCH$/d;
	s, xorg, extra/xorg,g;
	/xorg-drivers/d;
' {} +;
/root/instantARCH/ARCHinstall.sh
