#!/bin/sh
# Untracked files of the current git repository.
cd $gitdir
git status --porcelain | grep '??' | awk '{print $2}'
[ -z $1 ] && git status -s | grep \?\? |  awk '{ print $2 }' \
	>> $gitdir/info/exclude
elif [ $1 == rm ]; then
	rm -r `git status -s | grep \?\? |  awk '{ print $2 }'`
else
	git status -s | grep \?\? |  awk '{ print $2 }'
if [ $1 == exclude ]; then
	gitdir="`git rev-parse --absolute-git-dir`"
	echo '\n' >> $gitdir/info/exclude
	git status -s | grep \?\? |  awk '{ print $2 }' >> $gitdir/info/exclude
elif [ $1 == rm ]; then
	rm -r `git status -s | grep \?\? |  awk '{ print $2 }'`
