#!/bin/sh

: "
NAME
	Thunderbird and Firefox user.js Formatter
"

[ "$(basename "$1")" = 'user-overrides.js' ] || exit

# shellcheck disable=SC2094
grep -v 'user_pref("' "$1" | sed '
	s/^/user_pref("/;
	s/[;\t]/", /;
	s/$/);/;
' >> "$1" &&
sed -Ei '
	/^[^u/]/d;
	s/", ([^"tf[:digit:]].*)\);/", "\1"\);/;
' "$1"
# sort "$1" -o "$1"
